import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { clsx } from "clsx";

const iranSansFont = localFont({
  src: [
    {
      path: "../public/fonts/woff2/IRANSansX-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/woff2/IRANSansX-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={clsx("antialiased", iranSansFont.className)}
        style={iranSansFont.style}
      >
        {children}
      </body>
    </html>
  );
}
