import { Toaster } from "@/components/ui/sonner";
import QueryClientWrapper from "@/container/QueryClientWrapper/QueryClientWrapper";
import SessionWrapper from "@/container/SessionWrapper/SessionWrapper";
import { clsx } from "clsx";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { CartProvider } from "@/container/CartProvider/CartProvider";

const iranSansFont = localFont({
  src: [
    {
      path: "../public/fonts/woff2/IRANSansX-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/woff2/IRANSansX-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "pro shop",
  description: "Generated by pro shop development team",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="fa" dir="rtl">
      <body
        className={clsx("antialiased", iranSansFont.className)}
        style={iranSansFont.style}
      >
        <SessionWrapper session={session}>
          <QueryClientWrapper>
            <CartProvider>
              <Header />
              {children}
              <Footer />
            </CartProvider>
          </QueryClientWrapper>
        </SessionWrapper>
        <Toaster
          style={iranSansFont.style}
          className={iranSansFont.className}
          visibleToasts={10}
          closeButton
          richColors
          theme="light"
        />
      </body>
    </html>
  );
}
